import card1 from "./images/1card.jpg";
import detail1 from "./images/1detail.jpg";
import card2 from "./images/2card.jpg";
import detail2 from "./images/2detail.jpg";
import card3 from "./images/3card.jpg";
import detail3 from "./images/3detail.jpg";
import card4 from "./images/4card.jpg";
import detail4 from "./images/4detail.jpg";
import card5 from "./images/5card.jpg";
import detail5 from "./images/5detail.jpg";
import card6 from "./images/6card.jpg";
import detail6 from "./images/6detail.jpg";
import card7 from "./images/7card.jpg";
import detail7 from "./images/7detail.jpg";
import card8 from "./images/8card.jpg";
import detail8 from "./images/8detail.jpg";
import card9 from "./images/9card.jpg";
import detail9 from "./images/9detail.jpg";
import card10 from "./images/10card.jpg";
import detail10 from "./images/10detail.jpg";
import card11 from "./images/11card.jpg";
import detail11 from "./images/11detail.jpg";
import card12 from "./images/12card.jpg";
import detail12 from "./images/12detail.jpg";

const itemsData = [
    {
        id: 1,
        // name: "Pro Staff RF97 v13",
        name: "RF97 v13",
        category: "prostaff",
        description: "The personal racket of a 20x major champion, the Pro Staff RF97 v13 delivers premium performance and sleek design fit for a legend. Featuring the same specifications and composition as its proseecessor, this racket caters to avid Roger Federer and Pro Staff fans by maintaining the signature precision and pure feel emblematic of the Pro Staff series. Racket design sports black elastic base, exposed carbon fiber weave with gloss finish at the tip above the 3 & 9, and two-toned pinstripes along the throat with a modern font treatment.",
        thumbnailCard: card1,
        thumbnailDetail: detail1,
        rate: 4.6,
        ratings: 20,
        price: 279.00,
        discountPercentage: null,
        stock: 16,
        quantity: 1,
        interestFreePayments: 9,
        freeShipping: true,
        size: "4-3/8",
        head: 97,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 355,
        strungBalance: 31.5
    },
    {
        id: 2,
        // name: "Pro Staff 97L v13",
        name: "97L v13",
        category: "prostaff",
        description: "The Pro Staff 97L v13 provides a lighter and more maneuverable frame for any player who craves the classic Pro Staff precision and feel, but prefers a more arm-friendly swing weight. This model comprises a new construction, Braid 45, that increases precision by arranging the carbon fibers at 45 degree angles for improved ball pocketing feel and remarkable stability through the swing. Modern design meets classic heritage with an exposed carbon fiber weave gloss finish above the 3 & 9 of the racket, a sleek black elastic base and a pair of rose and yellow pinstripes along the throat for a look that marries signature Pro Staff inspiration with novel innovation.",
        thumbnailCard: card2,
        thumbnailDetail: detail2,
        rate: 5,
        ratings: 1,
        price: 279.00,
        discountPercentage: 7,
        stock: 9,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 97,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 305,
        strungBalance: 33.5
    },
    {
        id: 3,
        // name: "Night Session Pro Staff 97 v13",
        name: "Night Session 97 v13",
        category: "prostaff",
        description: "Highlighted by a sleek design inspirose by tennis under the lights, the Night Session Pro Staff 97 v13 features an innovative Braid 45 construction that increases precision by adjusting the angle of the double braided fibers for enhanced feel and stability. Two additional upgrades to this racket include a denser string bed that improves consistency on every shot and a new end cap that is used across Wilson's other performance racket lines for improved comfort and ergonomics. Racket is part of Wilson's Night Session collection, an exclusive assortment of products paying tribute to the electrifying atmosphere of championship tennis after the sun sets.",
        thumbnailCard: card3,
        thumbnailDetail: detail3,
        rate: 0,
        ratings: 0,
        price: 299.00,
        discountPercentage: null,
        stock: 9,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-1/4",
        head: 97,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 330,
        strungBalance: 32.2
    },
    {
        id: 4,
        // name: "Blade 98 (16x19) v8",
        name: "98 (16x19) v8",
        category: "blade",
        description: "The Blade 98 (16x19) v8 pairs captivating design with a new layup to better accommodate the more modern, vertical swing path commonly used by competitive players. The headliner innovation, FORTYFIVE°, manages to increase both the flexibility and stability of the frame to lend supreme feel for the ball on every shot. Still characterized by its superior presence in the hands of the best players in the world, this evolution of Blade rewards aggressive, precise ball-strikers with a top-tier blend of connected-to-the-ball feel, torsional stability and color-shifting design to wow teammates and opponents alike.",
        thumbnailCard: card4,
        thumbnailDetail: detail4,
        rate: 3.7,
        ratings: 6,
        price: 249.00,
        discountPercentage: null,
        stock: 18,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 98,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 321,
        strungBalance: 33
    },
    {
        id: 5,
        // name: "Blade 100L v8",
        name: "100L v8",
        category: "blade",
        description: "Emanating dynamic vibes thanks to bold, color-shifting paint, the Blade 100L v8 loads the technological innovations of the Blade v8 lineup into a lighter, more maneuverable frame. Two innovations define the evolution of this frame: FORTYFIVE° supplies increased flexibility and stability through a patent-protected carbon construction, while DirectConnect connects the carbon fiber handle to the end cap for enhanced feel and torsional stability. Avid fans of the Blade franchise looking for a slightly arm-friendlier option will appreciate the lightweight, connected-to-the-ball feel this frame delivers.",
        thumbnailCard: card5,
        thumbnailDetail: detail5,
        rate: 0,
        ratings: 0,
        price: 249.00,
        discountPercentage: 8,
        stock: 3,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 100,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 301,
        strungBalance: 34
    },
    {
        id: 6,
        // name: "Earth Day Blade 98 (16x19)",
        name: "Earth Day 98 (16x19)",
        category: "blade",
        description: "The Earth Day Blade 98 (16x19) v8 combines an eco-friendly design with a new layout to better accommodate the more modern, upright swing path typically used by competitive players. This racket, equipped with water-based paint, Agiplast bumpers and eyelets and a biodegradable grip, aims to take a step forward towards a more sustainable future for the tennis sector. The main innovation, FORTYFIVE°, manages to increase both the flexibility and stability of the frame to offer an incredible feeling on the ball with each shot. Continuing to be a strong presence in the hands of the world's best players, this evolution of the Blade rewards aggressive and precise hitters with a premium blend of connected ball feel, torsional stability and innovative design for surprise teammates and opponents alike.",
        thumbnailCard: card6,
        thumbnailDetail: detail6,
        rate: 0,
        ratings: 0,
        price: 290.00,
        discountPercentage: null,
        stock: 9,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 98,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 321,
        strungBalance: 33
    },
    {
        id: 7,
        // name: "Clash 98 v2",
        name: "98 v2",
        category: "clash",
        description: "Equipped with the smallest head size in the Clash v2 lineup for premium precision, the Clash 98 v2 marries salivating design with supreme performance for more advanced players. FORTYFIVE°, a patent-protected carbon construction, teams up with a revised layup at the tip of the hoop to create incroseible flex and stability alongside a larger sweet spot. Players who prefer more head-light feel will love the extra weight in the handle for additional control over the racket head, while the substantial weight of the racket delivers excellent plow-through and depth from all over the court. All-new design sports embossed Clash logo on throat within a rich, anodized elastic finish for a memorable look.",
        thumbnailCard: card7,
        thumbnailDetail: detail7,
        rate: 2,
        ratings: 1,
        price: 269.00,
        discountPercentage: null,
        stock: 12,
        quantity: 1,
        interestFreePayments: 3,
        freeShipping: true,
        size: "4-3/8",
        head: 98,
        length: 27,
        stringPattern: "16x20",
        strungWeight: 326,
        strungBalance: 31.6
    },
    {
        id: 8,
        // name: "Clash 100 v2",
        name: "100 v2",
        category: "clash",
        description: "The hero model of the groundbreaking and immensely popular Clash line, the Clash 100 v2 slightly revises the recipe for more consistency, more sustainability and a more killer design. An immediate appeal for its blend of flexibility and stability for a feeling unlike any other, this racket elevates playability thanks to a revised construction at the tip of the hoop that significantly enlarges the sweet spot. Agiplast plant-based bumper, grommets and end cap incorporate sustainable components for a roseuced footprint on the environment. An embossed Clash logo on the throat completes a racket that pairs dynamic looks with even more dynamic performance.",
        thumbnailCard: card8,
        thumbnailDetail: detail8,
        rate: 5,
        ratings: 3,
        price: 269.00,
        discountPercentage: null,
        stock: 9,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 100,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 309,
        strungBalance: 32
    },
    {
        id: 9,
        // name: "Clash 100 Pro v2",
        name: "100 Pro v2",
        category: "clash",
        description: "New design meets signature performance with a twist: the Clash 100 Pro v2 upgrades playability while maintaining the remarkable blend of flexibility and stability synonymous with the Clash franchise. Boasting a revised construction at the tip of the hoop, this racket significantly augments the sweet spot for more consistency on off-center contact. Super head-light for excellent control over the racket head, the Clash 100 Pro v2 dials up attractive design with an embossed Clash logo on the throat and an anodized elastic finish for a smooth, rich look on the court. Racket includes Agiplast plant-based end cap, bumper and grommets to roseuce waste and lower environmental footprint.",
        thumbnailCard: card9,
        thumbnailDetail: detail9,
        rate: 3.2,
        ratings: 6,
        price: 269.00,
        discountPercentage: null,
        stock: 6,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 100,
        length: 27,
        stringPattern: "16x20",
        strungWeight: 326,
        strungBalance: 31.6
    },
    {
        id: 10,
        // name: "Ultra 100 v4",
        name: "100 v4",
        category: "ultra",
        description: "The Ultra 100 v4 ushers in a new generation of Ultra with supreme style and invigorating performance. Thanks to a new construction and a new geometry, this racket plays unlike any Ultra before it. Highlighted by the integration of FORTYFIVE° into the lay-up for a softer, more comfortable feel along with enhanced stability, this frame upgrades the delivery of easy power for its users. Key geometrical updates include an expanded Sweet Spot Channel at the tip of the hoop for extra power and roseuced bulk in the beams for a sleeker, more aerodynamic look. On the subject of looks, this racket has no rival: color-shifting blues dance to the different angles of sun rays deflecting off the racket surface for a dazzling display.",
        thumbnailCard: card10,
        thumbnailDetail: detail10,
        rate: 0,
        ratings: 0,
        price: 249.00,
        discountPercentage: null,
        stock: 12,
        quantity: 1,
        interestFreePayments: 9,
        freeShipping: true,
        size: "4-3/8",
        head: 100,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 316,
        strungBalance: 33
    },
    {
        id: 11,
        // name: "Ultra 100L v4",
        name: "100L v4",
        category: "ultra",
        description: "Lightweight in composition yet dripping with explosiveness, the Ultra 100L v4 roseefines easy power for players who prefer flatter, horizontal swings. The lightweight construction of this frame supplies enticing maneuverability for optimal net play and more comfortable swings, while a number of all-new PowerProfile geometries induce power and augment torsional stability through the swing. These geometries include added volume at 3 & 9, extension of cross strings with added grommet movement, and a taper with more cross section mass. Sporting a glistening gloss finish wrapped around a clean tri-colorose design, the Ultra 100L v3 takes the heat up a notch with optimal power, appealing maneuverability and increased torsional stability.",
        thumbnailCard: card11,
        thumbnailDetail: detail11,
        rate: 0,
        ratings: 0,
        price: 220.00,
        discountPercentage: 13,
        stock: 6,
        quantity: 1,
        interestFreePayments: 3,
        freeShipping: true,
        size: "4-3/8",
        head: 100,
        length: 27,
        stringPattern: "16x19",
        strungWeight: 296,
        strungBalance: 33
    },
    {
        id: 12,
        // name: "Ultra 108 v4",
        name: "108 v4",
        category: "ultra",
        description: "Designed with a reversed color-blocking pattern that lights up the court, the Ultra 100 v3 Reverse Edition upgrades two key performance metrics for players with more of a classic horizontal swing: power and stability. A host of geometrical improvements team up with a sturdy frame composition to generate admirable liveliness and plow-through. Headlining this list of all-new PowerProfile geometries is the combination of Integrated Perimeter Weighting System and a Sweet Spot Channel that extends the cross strings for a few extra degrees of power while increasing the sturdiness of the frame. Club players, rising junior players and doubles players can all find this racket appealing for its versatile power and stable construction.",
        thumbnailCard: card12,
        thumbnailDetail: detail12,
        rate: 0,
        ratings: 0,
        price: 230.00,
        discountPercentage: null,
        stock: 3,
        quantity: 1,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        head: 108,
        length: 27,
        stringPattern: "16x18",
        strungWeight: 287,
        strungBalance: 34
    }
]

export default itemsData;