const itemsData = [
    {
        id: 1,
        name: "Pro Staff RF97 v13 Tennis Racket",
        category: "Rackets",
        subCategory: "Pro Staff",
        description: "The personal racket of a 20x major champion, the Pro Staff RF97 v13 delivers premium performance and sleek design fit for a legend. Featuring the same specifications and composition as its predecessor, this racket caters to avid Roger Federer and Pro Staff fans by maintaining the signature precision and pure feel emblematic of the Pro Staff series. Racket design sports black elastic base, exposed carbon fiber weave with gloss finish at the tip above the 3 & 9, and two-toned pinstripes along the throat with a modern font treatment. ",
        thumbnail: "https://www.wilson.com/en-us/media/catalog/product/W/R/WR043711U__64d7c67880e6d9400aea6113b2627a2e.png?dpr=5&fit=bounds&orient=1&quality=90&optimize=high&format=pjpg&auto=webp&enable=upscale&width=1536&height=711&canvas=7680%2C3555&bg-color=f5f5f5",
        rate: 4.6,
        ratings: 20,
        price: 279.00,
        discountPercentage: null,
        stock: 16,
        interestFreePayments: 9,
        freeShipping: true,
        size: "4-3/8",
        specifications: {
            head: 97,
            length: 27,
            stringPattern: "16x19",
            strungWeight: 355,
            strungBalance: 31.5
        }
    },
    {
        id: 2,
        name: "Pro Staff 97L v13 Tennis Racket",
        category: "Rackets",
        subCategory: "Pro Staff",
        description: "The Pro Staff 97L v13 provides a lighter and more maneuverable frame for any player who craves the classic Pro Staff precision and feel, but prefers a more arm-friendly swing weight. This model comprises a new construction, Braid 45, that increases precision by arranging the carbon fibers at 45 degree angles for improved ball pocketing feel and remarkable stability through the swing. Modern design meets classic heritage with an exposed carbon fiber weave gloss finish above the 3 & 9 of the racket, a sleek black elastic base and a pair of red and yellow pinstripes along the throat for a look that marries signature Pro Staff inspiration with novel innovation.",
        thumbnail: "https://www.wilson.com/en-us/media/catalog/product/W/R/WR043911U__d3684bdc543299b081df0fd50469c0ca.png?dpr=5&fit=bounds&orient=1&quality=90&optimize=high&format=pjpg&auto=webp&enable=upscale&width=1536&height=711&canvas=7680%2C3555&bg-color=f5f5f5",
        rate: 5,
        ratings: 1,
        price: 279.00,
        discountPercentage: 7,
        stock: 9,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        specifications: {
            head: 97,
            length: 27,
            stringPattern: "16x19",
            strungWeight: 305,
            strungBalance: 33.5
        }
    },
    {
        id: 3,
        name: "Blade 98 (16x19) v8 Tennis Racket",
        category: "Rackets",
        subCategory: "Blade",
        description: "The Blade 98 (16x19) v8 pairs captivating design with a new layup to better accommodate the more modern, vertical swing path commonly used by competitive players. The headliner innovation, FORTYFIVE°, manages to increase both the flexibility and stability of the frame to lend supreme feel for the ball on every shot. Still characterized by its superior presence in the hands of the best players in the world, this evolution of Blade rewards aggressive, precise ball-strikers with a top-tier blend of connected-to-the-ball feel, torsional stability and color-shifting design to wow teammates and opponents alike. ",
        thumbnail: "https://www.wilson.com/en-us/media/catalog/product/a/5/a5f13aff-703b-4870-9234-6c382cfc0b40_9he4h2zqw8mdesab.png?dpr=2&fit=bounds&orient=1&quality=95&optimize=high&format=pjpg&auto=webp&enable=upscale&width=778&height=950&canvas=1556%2C1900&bg-color=f5f5f5",
        rate: 3.7,
        ratings: 6,
        price: 249.00,
        discountPercentage: null,
        stock: 18,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        specifications: {
            head: 98,
            length: 27,
            stringPattern: "16x19",
            strungWeight: 321,
            strungBalance: 33
        }
    },
    {
        id: 4,
        name: "Blade 100L v8 Tennis Racket",
        category: "Rackets",
        subCategory: "Blade",
        description: "Emanating dynamic vibes thanks to bold, color-shifting paint, the Blade 100L v8 loads the technological innovations of the Blade v8 lineup into a lighter, more maneuverable frame. Two innovations define the evolution of this frame: FORTYFIVE° supplies increased flexibility and stability through a patent-protected carbon construction, while DirectConnect connects the carbon fiber handle to the end cap for enhanced feel and torsional stability. Avid fans of the Blade franchise looking for a slightly arm-friendlier option will appreciate the lightweight, connected-to-the-ball feel this frame delivers.",
        thumbnail: "https://www.wilson.com/en-us/media/catalog/product/3/f/3f8f5bf2-de0c-421c-b544-78a34e0500fd_w0aqnqhqfqi5xudy.png?dpr=5&fit=bounds&orient=1&quality=90&optimize=high&format=pjpg&auto=webp&enable=upscale&width=1536&height=711&canvas=7680%2C3555&bg-color=f5f5f5",
        rate: null,
        ratings: 0,
        price: 249.00,
        discountPercentage: 8,
        stock: 3,
        interestFreePayments: 6,
        freeShipping: true,
        size: "4-3/8",
        specifications: {
            head: 100,
            length: 27,
            stringPattern: "16x19",
            strungWeight: 301,
            strungBalance: 34
        }
    },
    {
        id: 4,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 5,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 6,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 7,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 8,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 9,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 10,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },
    {
        id: 11,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    },{
        id: 12,
        name: "",
        category: "",
        subCategory: "",
        description: "",
        thumbnail: "",
        rate: 0,
        ratings: 0,
        price: 0.00,
        discountPercentage: 0,
        stock: 0,
        interestFreePayments: 0,
        freeShipping: true,
        size: "",
        specifications: {
            head: 0,
            length: 0,
            stringPattern: "",
            strungWeight: 0,
            strungBalance: 0
        }
    }
]

export default itemsData;