const items = [
    {
        id: 1,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 2,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 3,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 4,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 5,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 6,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 7,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 8,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    }, 
    {
        id: 9,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 10,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 11,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    },
    {
        id: 12,
        name: "",
        category: "",
        description: "",
        thumbnail: "",
        rate: 1,
        price: 1,
        discount: 2,
        stock: 1,
        fees: 9,
        freeShipping: true,
    }
]